# General Config
title = "ssrjs"
description ="Full Stack JS/TS with Server Side Rendering"

[subfolders] 
public = {}

[subfolders.src]
pages = {} 
layouts = {} 
components = {} 

# Scripts
[scripts.npm]
"dev" = "astro dev"
"start" = "astro dev"
"build" = "astro build"
"preview" = "astro preview"

# Dependencies
[[deps.npm]]
name = "astro"
dev = true

[[deps.npm]]
name = "@astrojs/node"

[[deps.npm]]
name = "@astrojs/vue"

[[deps.npm]]
name= "vue"

[[deps.npm]]
name = "eslint-plugin-astro"
dev = true

[[deps.npm]]
name = "eslint-plugin-vue"
dev = true

[[deps.npm]]
name = "@typescript-eslint/parser"
dev = true

[[deps.npm]]
name = "eslint-plugin-jsx-a11y"
dev= true
