# SSRJS Stack - Full Stack JS/TS with Server Side Rendering

title = "ssrjs"

subfolders = ["src", "public", "src/pages", "src/layouts", "src/components"]

[dependencies.npm]
astro = {dev = true}
"@astrojs/vue" = "latest"
vue = "latest" 
