# SSRJS Stack - Full Stack JS/TS with Server Side Rendering

title = "ssrjs"

[subfolders] 
public = []
src = ["pages", "layouts", "components"] 

[dependencies]
npm = [
	{name = "astro"},
	{name = "@astrojs/vue"},
	{name= "vue"},
]
