# SSRJS Stack - Full Stack JS/TS with Server Side Rendering
title = "ssrjs"

[subfolders] 
public = []
src = ["pages", "layouts", "components"] 

[scripts]
npm = [
		{"dev" = "astro dev"},
		{"start" = "astro dev"},
		{"build" = "astro build"},
		{"preview" = "astro preview"}
]

[dependencies]
npm = [
	{name = "astro", dev = true, version = "^0.21.0", then=["npm run build", "npm run install"]},
	{name = "@astrojs/vue"},
	{name= "vue"},
]
