# General Config
title = "ssrjs"
description ="Full Stack JS/TS with Server Side Rendering"

[subfolders] 
public = {}

[subfolders.src]
# pages = {} 
layouts = {} 
components = {} 

# Scripts
[scripts.npm]
"dev" = "astro dev"
"start" = "astro dev"
"build" = "astro build"
"preview" = "astro preview"

# Dependencies
[[deps.npm]]
name = "astro"
dev = true
version = "latest"
then=[]

[[deps.npm]]
name = "@astrojs/vue"

[[deps.npm]]
name= "vue"
