# General Config
title = "tscli"
description = "TypeScript Node CLI Tool"

[[deps.npm]]
name="typescript"
dev= true

[[deps.npm]]
name = "commander"

[[deps.npm]]
name = "inquirer"

[[deps.npm]]
name = "chalk"

[[deps.npm]]
name = "cli-progress"
